###
POST http://localhost:3000/api/companies/register 
Content-Type: application/json

{
    "companyName": "Tech Innovators Inc.",
  "companySize": 50,
  "adminEmail": "admin@techinnovators.com",
  "adminPassword": "securePassword123",
  "contactEmail": "contact@techinnovators.com",
  "requirements": ["Create task"],
  "status": "PENDING"
}


###

POST http://localhost:3000/api/employees/add 
Content-Type: application/json

{
    "name":"jatin",
    "email":"jatin@gmail.com",
    "position":"admin",
    "companyDb":"company_solanki_and_sons_a5860"
}